name: PlatformIO Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python (required for PlatformIO)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Cache PlatformIO packages and build files
      - name: Cache PlatformIO
        uses: actions/cache@v3
        with:
          path: |
            ~/.platformio/packages
            ~/.platformio/lib
            ~/.platformio/platforms
            .pio
          key: platformio-${{ runner.os }}-${{ hashFiles('platformio.ini') }}
          restore-keys: |
            platformio-${{ runner.os }}-

      # Step 4: Install PlatformIO
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      # Step 5: Build the project
      - name: Build Project
        run: pio run

      # Step 6: Create a GitHub release and attach firmware
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: v1.0.0
          body: "Automated firmware build from PlatformIO"
          allowUpdates: true
          artifacts: .pio/build/**/firmware.bin
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}